/* Action Types */
export const STOREFRONT_VISIT_ACTION_TYPE = 'STOREFRONT_VISIT'
export const STOREFRONT_SAVE_ACTION_TYPE = 'STOREFRONT_SAVE'
export const LEAD_SENT_ACTION_TYPE = 'LEAD_SENT'
export const WEBSITE_CLICK_ACTION_TYPE = 'WEBSITE_CLICK'
export const CALL_INITIATED_ACTION_TYPE = 'CALL_INITIATED'
export const REVIEW_ACTION_TYPE = 'REVIEW'
export const COUPLE_MARKED_AS_BOOKED_TYPE = 'COUPLE_MARKED_AS_BOOKED'
export const VENDOR_MARKED_AS_BOOKED_TYPE = 'VENDOR_MARKED_AS_BOOKED'
export const EXPLICIT_REVIEW_ACTION_TYPE = 'EXPLICIT_REVIEW'
export const REAL_WEDDING_ACTION_TYPE = 'REAL_WEDDING'


/* Entry: Wedding Years */
const browserLocalTime = new Date()
const currentYear = browserLocalTime.getFullYear()
const yearMinus1  = (currentYear - 1).toString()
const yearCurrent = (currentYear).toString()
const yearPlus1   = (currentYear + 1).toString()
export const WEDDING_YEAR_MINUS_1_TYPE = yearMinus1
export const WEDDING_YEAR_CURRENT_TYPE = yearCurrent
export const WEDDING_YEAR_PLUS_1_TYPE  = yearPlus1

/* Filter Types */
export const ALL_ACTIONS_FILTER_TYPE = 'ALL_ACTIONS'
export const BOOKINGS_FILTER_TYPE = 'BOOKINGS'
export const PRE_ACTION_TYPES = [STOREFRONT_VISIT_ACTION_TYPE, STOREFRONT_SAVE_ACTION_TYPE, LEAD_SENT_ACTION_TYPE, WEBSITE_CLICK_ACTION_TYPE, CALL_INITIATED_ACTION_TYPE]
export const POST_ACTION_TYPES = [REVIEW_ACTION_TYPE, COUPLE_MARKED_AS_BOOKED_TYPE, VENDOR_MARKED_AS_BOOKED_TYPE, EXPLICIT_REVIEW_ACTION_TYPE, REAL_WEDDING_ACTION_TYPE]
export const WEDDING_YEAR_TYPES = [WEDDING_YEAR_PLUS_1_TYPE, WEDDING_YEAR_CURRENT_TYPE, WEDDING_YEAR_MINUS_1_TYPE]

/* ordering in 10x's for more intuitive grouping: "Wedding Year" in '50s' */
export const FILTERS_ORDER = new Map([
  [STOREFRONT_VISIT_ACTION_TYPE, 2],
  [STOREFRONT_SAVE_ACTION_TYPE, 3],
  [LEAD_SENT_ACTION_TYPE, 6],
  [WEBSITE_CLICK_ACTION_TYPE, 4],
  [CALL_INITIATED_ACTION_TYPE, 5],
  [REVIEW_ACTION_TYPE, 9],
  [EXPLICIT_REVIEW_ACTION_TYPE, 10],
  [COUPLE_MARKED_AS_BOOKED_TYPE, 7],
  [VENDOR_MARKED_AS_BOOKED_TYPE, 8],
  [ALL_ACTIONS_FILTER_TYPE, 100],
  [BOOKINGS_FILTER_TYPE, 12],
  [WEDDING_YEAR_MINUS_1_TYPE, 52],
  [WEDDING_YEAR_CURRENT_TYPE, 51],
  [WEDDING_YEAR_PLUS_1_TYPE, 50],
  [REAL_WEDDING_ACTION_TYPE, 11]
])

export const FILTER_LABELS = new Map([
  [STOREFRONT_VISIT_ACTION_TYPE, 'Visits'],
  [STOREFRONT_SAVE_ACTION_TYPE, 'Saves'],
  [LEAD_SENT_ACTION_TYPE, 'Leads'],
  [WEBSITE_CLICK_ACTION_TYPE, 'Clicks to Website/Social'],
  [CALL_INITIATED_ACTION_TYPE, 'Calls'],
  [REVIEW_ACTION_TYPE, 'Reviews'],
  [COUPLE_MARKED_AS_BOOKED_TYPE, 'Couple Marked as Booked'],
  [VENDOR_MARKED_AS_BOOKED_TYPE, 'Vendor Marked as Booked'],
  [ALL_ACTIONS_FILTER_TYPE, 'Clear All'],
  [BOOKINGS_FILTER_TYPE, 'Bookings'],
  [REAL_WEDDING_ACTION_TYPE, 'Real Wedding'],
  [EXPLICIT_REVIEW_ACTION_TYPE, 'Review + Confirmed'],
  [WEDDING_YEAR_MINUS_1_TYPE, yearMinus1],
  [WEDDING_YEAR_CURRENT_TYPE, yearCurrent],
  [WEDDING_YEAR_PLUS_1_TYPE, yearPlus1]
])

/* Action/Entry: Groups */
export const FILTER_GROUPS = new Map([
  ['PRE_ACTION_TYPES', PRE_ACTION_TYPES],
  ['POST_ACTION_TYPES', POST_ACTION_TYPES],
  ['WEDDING_YEAR_TYPES', WEDDING_YEAR_TYPES,]
])

export const FILTER_GROUP_LABELS = new Map([
  ['PRE_ACTION_TYPES', 'Pre-Actions'],
  ['POST_ACTION_TYPES', 'Booking Actions'],
  ['WEDDING_YEAR_TYPES', 'Wedding Date']
])
