export const SET_LOADING = "SET_LOADING";
export const LOAD_COUPLES_JOURNEY = "LOAD_COUPLES_JOURNEY";
export const LOAD_FILTERS = "LOAD_FILTERS";
export const LOAD_SELECTED_FILTERS = "LOAD_SELECTED_FILTERS"